# Generated by Django 5.0.1 on 2025-05-30 22:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('demos', '0001_squashed_0033_alter_game_infinite_mac_custom_image'), ('demos', '0034_alter_website_gog_alter_website_macintosh_garden_and_more'), ('demos', '0035_alter_source_infinite_mac_url_alter_source_url'), ('demos', '0036_alter_game_infinite_mac_custom_image'), ('demos', '0037_alter_game_infinite_mac_custom_image'), ('demos', '0038_game_aka'), ('demos', '0039_remove_language_game_game_languages_source_disc_and_more'), ('demos', '0040_alter_source_game'), ('demos', '0041_alter_source_options'), ('demos', '0042_magazine_blurb'), ('demos', '0043_source_blurb'), ('demos', '0044_game_contributor_source_contributor'), ('demos', '0045_game_contributor_url_source_contributor_url'), ('demos', '0046_country_remove_magazine_language_alter_source_year_and_more'), ('demos', '0047_source_images'), ('demos', '0048_source_magazine_embed_url'), ('demos', '0049_alter_source_url'), ('demos', '0050_alter_source_options_source_disc2_infinite_mac_url_and_more'), ('demos', '0051_alter_source_disc2_infinite_mac_url_and_more'), ('demos', '0052_source_added'), ('demos', '0053_magazine_image'), ('demos', '0054_explore'), ('demos', '0055_website_github_website_wayback_machine'), ('demos', '0056_country_display_order'), ('demos', '0057_alter_source_options_alter_source_month'), ('demos', '0058_website_mac_source_ports'), ('demos', '0059_source_infinite_mac_osx_machine_and_more'), ('demos', '0060_alter_source_infinite_mac_machine_and_more')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=200, verbose_name='Game')),
                ('year', models.IntegerField(default=2000, verbose_name='Published')),
                ('filename', models.CharField(max_length=100, verbose_name='PowerPC/Universal file name')),
                ('readme_txt', models.BooleanField(default=False, verbose_name='README.txt')),
                ('readme_html', models.BooleanField(default=False, verbose_name='README.html')),
                ('added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Added')),
                ('slug', models.SlugField(unique=True)),
                ('screens', models.IntegerField(default=0, verbose_name='Screenshots')),
                ('blurb', models.TextField(blank=True, verbose_name='Blurb')),
                ('infinite_mac_machine', models.CharField(blank=True, choices=[('', 'NONE'), ('1996/System 7.5.3?machine=Quadra+650', '68040 System 7.5.3'), ('1998/Mac OS 8.1?machine=Power+Macintosh+9500', 'PowerPC 604 Mac OS 8.1'), ('1999/Mac OS 9.0?machine=Power+Macintosh+9500', 'PowerPC 604 Mac OS 9.0')], default=False, max_length=200, verbose_name='Infinite Mac Prebuilt Machine')),
                ('readme_pdf', models.BooleanField(default=False, verbose_name='README.pdf')),
                ('filename_68k', models.CharField(blank=True, max_length=100, verbose_name='68k File name')),
                ('infinite_mac_custom_image', models.CharField(blank=True, choices=[('', 'NONE'), ('Quadra+650', 'Quadra 650'), ('Power+Macintosh+9500&ram=32M', 'Power Macintosh 9500'), ('Power+Macintosh+9500&ram=64M', 'Power Macintosh 9500 64MB')], default=False, max_length=200, verbose_name='Infinite Mac Custom Image')),
                ('aka', models.CharField(blank=True, max_length=200, verbose_name='aka')),
            ],
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloads', models.IntegerField(blank=True, default=0)),
                ('game', models.ForeignKey(auto_created=True, on_delete=django.db.models.deletion.CASCADE, to='demos.game')),
            ],
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plays', models.IntegerField(blank=True, default=0)),
                ('game', models.ForeignKey(auto_created=True, on_delete=django.db.models.deletion.CASCADE, to='demos.game')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('iso', models.CharField(max_length=2, verbose_name='ISO 639-1 Code')),
                ('icon', models.CharField(max_length=8, verbose_name='Icon')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='languages',
            field=models.ManyToManyField(blank=True, to='demos.language'),
        ),
        migrations.AddField(
            model_name='game',
            name='contributor',
            field=models.CharField(blank=True, max_length=200, verbose_name='Contributed by'),
        ),
        migrations.AddField(
            model_name='game',
            name='contributor_url',
            field=models.URLField(blank=True, verbose_name='Contributor URL'),
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('iso', models.CharField(max_length=2, verbose_name='ISO 3166 Code')),
                ('icon', models.CharField(max_length=8, verbose_name='Icon')),
                ('display_order', models.IntegerField(default=0, verbose_name='Display order')),
            ],
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magazine', models.CharField(max_length=200, verbose_name='Magazine')),
                ('url', models.URLField(blank=True, verbose_name='Webpage')),
                ('slug', models.SlugField(unique=True)),
                ('blurb', models.TextField(blank=True, verbose_name='Blurb')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='demos.country')),
                ('image', models.BooleanField(default=False, verbose_name='Has image?')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('url', models.URLField(blank=True, verbose_name='Webpage')),
                ('game', models.ManyToManyField(blank=True, to='demos.game')),
                ('infinite_mac_url', models.URLField(blank=True, max_length=500, verbose_name='ISO/DMG URL')),
                ('magazine_url', models.URLField(blank=True, verbose_name='Magazine URL')),
                ('slug', models.SlugField(unique=True)),
                ('infinite_mac_machine', models.CharField(blank=True, choices=[('', 'NONE'), ('1996/System 7.5.3?machine=Quadra+650', '68040 System 7.5.3'), ('1998/Mac OS 8.1?machine=Power+Macintosh+9500', 'PowerPC 604 Mac OS 8.1'), ('1999/Mac OS 9.0?machine=Power+Macintosh+9500', 'PowerPC 604 Mac OS 9.0'), ('2001/Mac OS X 10.1?machine=Power+Macintosh+G3+(Beige)', 'Mac OS X 10.1')], default=False, max_length=200, verbose_name='Infinite Mac Machine')),
                ('month', models.IntegerField(blank=True, choices=[(1, 'Jan'), (2, 'Feb'), (3, 'Mar'), (4, 'Apr'), (5, 'May'), (6, 'Jun'), (7, 'Jul'), (8, 'Aug'), (9, 'Sept'), (10, 'Oct'), (11, 'Nov'), (12, 'Dec'), (13, 'Holiday')], default=None, null=True, verbose_name='Month')),
                ('year', models.IntegerField(blank=True, default=2000, null=True, verbose_name='Year')),
                ('disc', models.IntegerField(blank=True, default=None, null=True, verbose_name='Disc #')),
                ('issue_name', models.CharField(blank=True, max_length=200, verbose_name='Issue Name')),
                ('issue_number', models.IntegerField(blank=True, default=None, null=True, verbose_name='Issue #')),
                ('volume', models.IntegerField(blank=True, default=None, null=True, verbose_name='Volume #')),
                ('magazine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='demos.magazine')),
                ('blurb', models.TextField(blank=True, verbose_name='Blurb')),
                ('contributor', models.CharField(blank=True, max_length=200, verbose_name='Contributed by')),
                ('contributor_url', models.URLField(blank=True, verbose_name='Contributor URL')),
                ('images', models.IntegerField(default=0, verbose_name='Images')),
                ('magazine_embed_url', models.URLField(blank=True, verbose_name='Embeddable Magazine URL')),
                ('disc2_infinite_mac_url', models.URLField(blank=True, max_length=500, verbose_name='Disc 2 ISO/DMG URL')),
                ('disc2_url', models.URLField(blank=True, verbose_name='Disc 2 Webpage')),
                ('added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Added')),
                ('infinite_mac_osx_machine', models.CharField(blank=True, choices=[('', 'NONE'), ('1996/System 7.5.3?machine=Quadra+650', '68040 System 7.5.3'), ('1998/Mac OS 8.1?machine=Power+Macintosh+9500', 'PowerPC 604 Mac OS 8.1'), ('1999/Mac OS 9.0?machine=Power+Macintosh+9500', 'PowerPC 604 Mac OS 9.0'), ('2001/Mac OS X 10.1?machine=Power+Macintosh+G3+(Beige)', 'Mac OS X 10.1')], default=False, max_length=200, verbose_name='Infinite Mac OS X Machine')),
            ],
            options={
                'ordering': ['magazine', 'year', 'month', 'volume', 'issue_number', 'disc'],
            },
        ),
        migrations.CreateModel(
            name='Explore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explores', models.IntegerField(blank=True, default=0)),
                ('source', models.ForeignKey(auto_created=True, on_delete=django.db.models.deletion.CASCADE, to='demos.source')),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('wikipedia', models.URLField(blank=True, verbose_name='Wikipedia')),
                ('steam', models.URLField(blank=True, verbose_name='Steam')),
                ('gog', models.URLField(blank=True, verbose_name='GOG')),
                ('macintosh_repository', models.URLField(blank=True, verbose_name='Macintosh Repository')),
                ('macintosh_garden', models.URLField(blank=True, verbose_name='Macintosh Garden')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demos.game')),
                ('mobygames', models.URLField(blank=True, verbose_name='MobyGames')),
                ('github', models.URLField(blank=True, verbose_name='GitHub')),
                ('wayback_machine', models.URLField(blank=True, verbose_name='Wayback Machine')),
                ('mac_source_ports', models.URLField(blank=True, verbose_name='Mac Source Ports')),
            ],
        ),
        migrations.AlterField(
            model_name='game',
            name='infinite_mac_machine',
            field=models.CharField(blank=True, choices=[('', 'NONE'), ('1996/System 7.5.3?machine=Quadra+650', '68040 System 7.5.3'), ('1998/Mac OS 8.1?machine=Power+Macintosh+9500', 'PowerPC 604 Mac OS 8.1'), ('1999/Mac OS 9.0?machine=Power+Macintosh+9500', 'PowerPC 604 Mac OS 9.0'), ('2001/Mac OS X 10.1?machine=Power+Macintosh+G3+(Beige)', 'Mac OS X 10.1')], default=False, max_length=200, verbose_name='Infinite Mac Prebuilt Machine'),
        ),
    ]
