# Generated by Django 5.0.1 on 2025-07-14 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('demos', '0002_virtualmachine_alter_game_infinite_mac_machine_and_more'), ('demos', '0003_alter_game_infinite_mac_machine_and_more'), ('demos', '0004_alter_game_virtual_machine_and_more')]

    dependencies = [
        ('demos', '0001_demos'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, verbose_name='Description')),
                ('machine', models.CharField(max_length=100, verbose_name='Machine configuration')),
                ('disk', models.CharField(blank=True, max_length=50, verbose_name='Disk name')),
            ],
        ),
        migrations.AlterField(
            model_name='game',
            name='infinite_mac_machine',
            field=models.CharField(blank=True, choices=[('', 'NONE'), ('1996/System 7.5.3?machine=Quadra+650', '68040 System 7.5.3'), ('1998/Mac OS 8.1?machine=Power+Macintosh+9500', 'PowerPC 604 Mac OS 8.1'), ('1999/Mac OS 9.0?machine=Power+Macintosh+9500', 'PowerPC 604 Mac OS 9.0'), ('2001/Mac OS X 10.1?machine=Power+Macintosh+G3+(Beige)', 'Mac OS X 10.1')], default=False, max_length=200, verbose_name='Infinite Mac Prebuilt Machine'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='demos.country'),
        ),
        migrations.AlterField(
            model_name='source',
            name='infinite_mac_machine',
            field=models.CharField(blank=True, choices=[('', 'NONE'), ('1996/System 7.5.3?machine=Quadra+650', '68040 System 7.5.3'), ('1998/Mac OS 8.1?machine=Power+Macintosh+9500', 'PowerPC 604 Mac OS 8.1'), ('1999/Mac OS 9.0?machine=Power+Macintosh+9500', 'PowerPC 604 Mac OS 9.0'), ('2001/Mac OS X 10.1?machine=Power+Macintosh+G3+(Beige)', 'Mac OS X 10.1')], default=False, max_length=200, verbose_name='Infinite Mac Machine'),
        ),
        migrations.AlterField(
            model_name='source',
            name='infinite_mac_osx_machine',
            field=models.CharField(blank=True, choices=[('', 'NONE'), ('1996/System 7.5.3?machine=Quadra+650', '68040 System 7.5.3'), ('1998/Mac OS 8.1?machine=Power+Macintosh+9500', 'PowerPC 604 Mac OS 8.1'), ('1999/Mac OS 9.0?machine=Power+Macintosh+9500', 'PowerPC 604 Mac OS 9.0'), ('2001/Mac OS X 10.1?machine=Power+Macintosh+G3+(Beige)', 'Mac OS X 10.1')], default=False, max_length=200, verbose_name='Infinite Mac OS X Machine'),
        ),
        migrations.AlterField(
            model_name='source',
            name='magazine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='demos.magazine'),
        ),
        migrations.AddField(
            model_name='game',
            name='virtual_machine',
            field=models.ForeignKey(limit_choices_to=models.Q(('disk__exact', '')), null=True, on_delete=django.db.models.deletion.SET_NULL, to='demos.virtualmachine'),
        ),
        migrations.AddField(
            model_name='source',
            name='disc2_osx_virtual_machine',
            field=models.ForeignKey(limit_choices_to=models.Q(('disk__exact', ''), _negated=True), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_disc2_osx_virtual_machine', to='demos.virtualmachine', verbose_name='Disc 2 Mac OS X Virtual machine'),
        ),
        migrations.AddField(
            model_name='source',
            name='disc2_virtual_machine',
            field=models.ForeignKey(limit_choices_to=models.Q(('disk__exact', ''), _negated=True), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_disc2_virtual_machine', to='demos.virtualmachine', verbose_name='Disc 2 Virtual machine'),
        ),
        migrations.AddField(
            model_name='source',
            name='osx_virtual_machine',
            field=models.ForeignKey(limit_choices_to=models.Q(('disk__exact', ''), _negated=True), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_osx_virtual_machine', to='demos.virtualmachine', verbose_name='Mac OS X Virtual machine'),
        ),
        migrations.AddField(
            model_name='source',
            name='virtual_machine',
            field=models.ForeignKey(limit_choices_to=models.Q(('disk__exact', ''), _negated=True), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_virtual_machine', to='demos.virtualmachine'),
        ),
    ]
