# Generated by Django 5.0.1 on 2025-07-14 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demos', '0002_virtualmachine_alter_game_infinite_mac_machine_and_more_squashed_0004_alter_game_virtual_machine_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='disc2_osx_virtual_machine',
        ),
        migrations.RemoveField(
            model_name='source',
            name='disc2_virtual_machine',
        ),
    ]
