# Generated by Django 5.0.1 on 2025-07-15 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demos', '0005_remove_source_disc2_osx_virtual_machine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='virtual_machine',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('disk__exact', '')), null=True, on_delete=django.db.models.deletion.SET_NULL, to='demos.virtualmachine'),
        ),
        migrations.AlterField(
            model_name='source',
            name='osx_virtual_machine',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('disk__exact', ''), _negated=True), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_osx_virtual_machine', to='demos.virtualmachine', verbose_name='Mac OS X Virtual machine'),
        ),
        migrations.AlterField(
            model_name='source',
            name='virtual_machine',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('disk__exact', ''), _negated=True), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_virtual_machine', to='demos.virtualmachine'),
        ),
    ]
