# Generated by Django 5.0.1 on 2025-07-15 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demos', '0006_alter_game_virtual_machine_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='infinite_mac_custom_image',
        ),
        migrations.RemoveField(
            model_name='game',
            name='infinite_mac_machine',
        ),
        migrations.RemoveField(
            model_name='source',
            name='infinite_mac_machine',
        ),
        migrations.RemoveField(
            model_name='source',
            name='infinite_mac_osx_machine',
        ),
    ]
