# Generated by Django 5.0.1 on 2025-07-31 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demos', '0007_remove_game_infinite_mac_custom_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='virtual_machine_height',
            field=models.IntegerField(choices=[(480, 'height480'), (600, 'height600'), (768, 'height768')], default=480),
        ),
        migrations.AddField(
            model_name='game',
            name='virtual_machine_width',
            field=models.IntegerField(choices=[(640, 'width640'), (800, 'width800'), (1024, 'width1024')], default=640),
        ),
    ]
