# Generated by Django 5.0.1 on 2025-07-31 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demos', '0008_game_virtual_machine_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='disc2_discmaster',
            field=models.URLField(blank=True, verbose_name='Disc 2 DiscMaster URL'),
        ),
        migrations.AddField(
            model_name='source',
            name='discmaster',
            field=models.URLField(blank=True, verbose_name='DiscMaster URL'),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='website_description',
            field=models.CharField(blank=True, max_length=50, verbose_name='Website description'),
        ),
    ]
