# Generated by Django 5.0.1 on 2026-01-30 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demos', '0009_source_disc2_discmaster_source_discmaster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='filename_3',
            field=models.CharField(blank=True, max_length=100, verbose_name='Download 3 File name'),
        ),
        migrations.AddField(
            model_name='source',
            name='disc3_discmaster',
            field=models.URLField(blank=True, verbose_name='Disc 3 DiscMaster URL'),
        ),
        migrations.AddField(
            model_name='source',
            name='disc3_infinite_mac_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Disc 3 ISO/DMG URL'),
        ),
        migrations.AddField(
            model_name='source',
            name='disc3_url',
            field=models.URLField(blank=True, verbose_name='Disc 3 Webpage'),
        ),
        migrations.AddField(
            model_name='source',
            name='disc4_discmaster',
            field=models.URLField(blank=True, verbose_name='Disc 4 DiscMaster URL'),
        ),
        migrations.AddField(
            model_name='source',
            name='disc4_infinite_mac_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Disc 4 ISO/DMG URL'),
        ),
        migrations.AddField(
            model_name='source',
            name='disc4_url',
            field=models.URLField(blank=True, verbose_name='Disc 4 Webpage'),
        ),
        migrations.AlterField(
            model_name='game',
            name='filename',
            field=models.CharField(max_length=100, verbose_name='Download file name'),
        ),
        migrations.AlterField(
            model_name='game',
            name='filename_68k',
            field=models.CharField(blank=True, max_length=100, verbose_name='Download 2 File name'),
        ),
    ]
